### How to use this document
# 1. Fill in your info
# 2. Re-excecute the build in the command line with: bundle exec jekyll serve
# 3. Push to github
title: IS445 Viz Project
description: Data visualization project nusiance complaints
theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
